export const SinglePage = "/details/:id";
export const HomePage = "/";
export const Admin = "/admin";
export const Desc= SinglePage+'/description';
export const Info= SinglePage+'/information';
export const Rev= SinglePage+'/review';
export const Prod = Admin+'/products';
export const User = Admin+'/users';
export const Cat = Admin+'/categories';
